version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kanban_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kanban
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


  backend:
    build: ./kanban-backend
    container_name: kanban_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/kanban?schema=public"
    depends_on:
      - postgres
    volumes:
      - ./kanban-backend:/app
      - /app/node_modules

  frontend:
    build: ./kanban-frontend
    container_name: kanban_frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:3000"
    volumes:
      - ./kanban-frontend:/app
      - /app/node_modules

volumes:
  postgres_data: